package ntut.csie.test.ExceptionThrownFromFinallyBlock;

import org.junit.Test;
import ntut.csie.RobustaUtils.AspectJSwitch;
import ntut.csie.RobustaUtils.CustomRobustaException;
import org.junit.Assert;
import java.lang.reflect.Method;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartUtils;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

import java.io.File;
import java.io.IOException;

public class testChartUtilsMethodUseAspetctJ {

	private AspectJSwitch aspectJSwitch = AspectJSwitch.getInstance();

	@Test
	public void testCloseThrowExceptionInSaveChartAsPNG() {
		aspectJSwitch.initResponse();
		aspectJSwitch.addResponse("writeChartAsPNG/f(CustomRobustaException)");
		aspectJSwitch.addResponse("close/f(IOException)");
		aspectJSwitch.toFirstResponse();
		try{
			DefaultPieDataset dataset = new DefaultPieDataset( );
		    dataset.setValue("IPhone 5s", new Double( 20 ) );
		    dataset.setValue("SamSung Grand", new Double( 20 ) );
		    dataset.setValue("MotoG", new Double( 40 ) );
		    dataset.setValue("Nokia Lumia", new Double( 10 ) );
		    JFreeChart chart = ChartFactory.createPieChart(
		    "Mobile Sales",   // chart title
		    dataset,          // data
		    true,             // include legend
		    true,
		    false);
		    int width = 640;   /* Width of the image */
		    int height = 480;  /* Height of the image */
		    File pieChart = new File( "PieChart.png" );
		    ChartUtils.saveChartAsPNG( pieChart , chart , width , height, null);
		    
		    JLabel lbl = new JLabel(new ImageIcon("PieChart.png"));
		    JOptionPane.showMessageDialog(null, lbl, "ImageDialog", 
		                                 JOptionPane.PLAIN_MESSAGE, null);
		} catch (CustomRobustaException e) {
			JOptionPane.showMessageDialog(null, e.getMessage());
			e.printStackTrace();
			Assert.assertEquals("This Exception is thrown from try/catch block, so the bad smell is removed.",e.getMessage());
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, e.getMessage());
			e.printStackTrace();
			Assert.fail("Exception is thrown from finally block.");
		}
	}
}